
<script type="text/javascript">
	jQuery(function(){	
		MeetingList.init();		
	});
	

	
</script>


<div id="meetings-list">
	<h2>Meetings</h2>
	<div id="actionTriggers">				
		<a href="/meeting/create/">Nytt nettmøte</a>		
	</div>	
	<div id="theListTop">
		<div class="listTopName">Tittel</div>
		<div class="listDescription">Beskrivelse</div>
		<div class="Name"># Q/A</div>
	</div>
	<div id="theList"></div>
</div>



